import React from "react";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./../globals.css";
import {AppProvider} from "@/app/AppProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default async function RootLayout({children,params}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;
    const messages = await getMessages();
    return <>
        <html
            lang={locale}
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <AppProvider >
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <body className="min-h-full flex flex-col">{children}</body>
                </NextIntlClientProvider>
            </AppProvider>
        </html>
    </>
}