import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateDB1777192612151 implements MigrationInterface {
    name = 'UpdateDB1777192612151'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`CREATE TABLE \`product_attributes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_attribute_values\` (\`id\` int NOT NULL AUTO_INCREMENT, \`value\` varchar(255) NOT NULL, \`attributeId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories_attributes_product_attributes\` (\`categoriesId\` int NOT NULL, \`productAttributesId\` int NOT NULL, INDEX \`IDX_5b226d6766aea1a153dac33158\` (\`categoriesId\`), INDEX \`IDX_c2497fdca890167755b9ac2798\` (\`productAttributesId\`), PRIMARY KEY (\`categoriesId\`, \`productAttributesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products_attribute_values_product_attribute_values\` (\`productsId\` int NOT NULL, \`productAttributeValuesId\` int NOT NULL, INDEX \`IDX_ec3943beb5bd3ad2e772790783\` (\`productsId\`), INDEX \`IDX_8e126322ba391c4b73482445b9\` (\`productAttributeValuesId\`), PRIMARY KEY (\`productsId\`, \`productAttributeValuesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD UNIQUE INDEX \`IDX_420d9f679d41281f282f5bc7d0\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`metaTitle\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`metaDescription\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`metaKeywords\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`mpath\` varchar(255) NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD UNIQUE INDEX \`IDX_464f927ae360106b783ed0b410\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`module\` \`module\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_fb2e442d14add3cefbdf33c4561\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`refreshToken\` \`refreshToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`dateOfBirth\` \`dateOfBirth\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginAt\` \`lastLoginAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`role_id\` \`role_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`short_description\` \`short_description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` DROP FOREIGN KEY \`FK_a16d35fd18ba21ee968a0081625\``);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`endDate\` \`endDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_db2d0ea722e16e0fe8ab3bce111\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variant_id\` \`variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_f5221735ace059250daac9d9803\``);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paymentMethod\` \`paymentMethod\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` CHANGE \`alt\` \`alt\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_fb2e442d14add3cefbdf33c4561\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` ADD CONSTRAINT \`FK_155f225a411a7955058946be337\` FOREIGN KEY (\`attributeId\`) REFERENCES \`product_attributes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` ADD CONSTRAINT \`FK_a16d35fd18ba21ee968a0081625\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_db2d0ea722e16e0fe8ab3bce111\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_f5221735ace059250daac9d9803\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories_attributes_product_attributes\` ADD CONSTRAINT \`FK_5b226d6766aea1a153dac33158f\` FOREIGN KEY (\`categoriesId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`categories_attributes_product_attributes\` ADD CONSTRAINT \`FK_c2497fdca890167755b9ac2798a\` FOREIGN KEY (\`productAttributesId\`) REFERENCES \`product_attributes\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`products_attribute_values_product_attribute_values\` ADD CONSTRAINT \`FK_ec3943beb5bd3ad2e7727907839\` FOREIGN KEY (\`productsId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`products_attribute_values_product_attribute_values\` ADD CONSTRAINT \`FK_8e126322ba391c4b73482445b92\` FOREIGN KEY (\`productAttributeValuesId\`) REFERENCES \`product_attribute_values\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`products_attribute_values_product_attribute_values\` DROP FOREIGN KEY \`FK_8e126322ba391c4b73482445b92\``);
        await queryRunner.query(`ALTER TABLE \`products_attribute_values_product_attribute_values\` DROP FOREIGN KEY \`FK_ec3943beb5bd3ad2e7727907839\``);
        await queryRunner.query(`ALTER TABLE \`categories_attributes_product_attributes\` DROP FOREIGN KEY \`FK_c2497fdca890167755b9ac2798a\``);
        await queryRunner.query(`ALTER TABLE \`categories_attributes_product_attributes\` DROP FOREIGN KEY \`FK_5b226d6766aea1a153dac33158f\``);
        await queryRunner.query(`ALTER TABLE \`payment\` DROP FOREIGN KEY \`FK_f5221735ace059250daac9d9803\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_db2d0ea722e16e0fe8ab3bce111\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` DROP FOREIGN KEY \`FK_a16d35fd18ba21ee968a0081625\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`product_attribute_values\` DROP FOREIGN KEY \`FK_155f225a411a7955058946be337\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_fb2e442d14add3cefbdf33c4561\``);
        await queryRunner.query(`ALTER TABLE \`images\` CHANGE \`alt\` \`alt\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` CHANGE \`paymentMethod\` \`paymentMethod\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_f5221735ace059250daac9d9803\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_db2d0ea722e16e0fe8ab3bce111\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`variant_id\` \`variant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`endDate\` \`endDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product_price_history\` ADD CONSTRAINT \`FK_a16d35fd18ba21ee968a0081625\` FOREIGN KEY (\`variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`short_description\` \`short_description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`role_id\` \`role_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`lastLoginAt\` \`lastLoginAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`dateOfBirth\` \`dateOfBirth\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`refreshToken\` \`refreshToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_fb2e442d14add3cefbdf33c4561\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`module\` \`module\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP INDEX \`IDX_464f927ae360106b783ed0b410\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`mpath\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`metaKeywords\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`metaDescription\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`metaTitle\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP INDEX \`IDX_420d9f679d41281f282f5bc7d0\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`slug\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e126322ba391c4b73482445b9\` ON \`products_attribute_values_product_attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_ec3943beb5bd3ad2e772790783\` ON \`products_attribute_values_product_attribute_values\``);
        await queryRunner.query(`DROP TABLE \`products_attribute_values_product_attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_c2497fdca890167755b9ac2798\` ON \`categories_attributes_product_attributes\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b226d6766aea1a153dac33158\` ON \`categories_attributes_product_attributes\``);
        await queryRunner.query(`DROP TABLE \`categories_attributes_product_attributes\``);
        await queryRunner.query(`DROP TABLE \`product_attribute_values\``);
        await queryRunner.query(`DROP TABLE \`product_attributes\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
