import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {store} from "@/src/redux/store";
import {Provider} from "react-redux";
import {AppProvider} from "@/app/AppProvider";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import {routing} from "@/messages/routing";
import {notFound} from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: {
  children: React.ReactNode;
  // params: Promise<{ locale: string }>;
}) {
  // const { locale } = await params;
  // if (!routing.locales.includes(locale as any)) {
  //   notFound();
  // }
  // const messages = await getMessages();
  return <AppProvider >
    <html
      lang={'en'}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/*<NextIntlClientProvider locale={locale} messages={messages}>*/}
        <body className="min-h-full flex flex-col">{children}</body>
      {/*</NextIntlClientProvider>*/}
    </html>
  </AppProvider>
}
