export const PERMISSIONS_CODE = {
  USER: {
    VIEW: 'USER_VIEW',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },
  PRODUCT: {
    VIEW: 'PRODUCT_VIEW',
    CREATE: 'PRODUCT_CREATE',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
  },
  CATEGORY: {
    VIEW: 'CATEGORY_VIEW',
    CREATE: 'CATEGORY_CREATE',
    UPDATE: 'CATEGORY_UPDATE',
    DELETE: 'CATEGORY_DELETE',
  },
  ORDER: {
    VIEW: 'ORDER_VIEW',
    CREATE: 'ORDER_CREATE',
    UPDATE: 'ORDER_UPDATE',
    DELETE: 'ORDER_DELETE',
  },

};
